import = ["/home/newird/.config/alacritty/catppucin.toml", "/home/newird/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false

[font]
size = 14.0
[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 15
y = 15
