#!/usr/bin/env fish
abbr -a arch   uu-arch  
abbr -a base32   uu-base32  
abbr -a base64   uu-base64  
abbr -a basename   uu-basename  
abbr -a basenc   uu-basenc  
abbr -a chmod   uu-chmod  
abbr -a chown   uu-chown  
abbr -a chroot   uu-chroot  
abbr -a cp  uu-cp
abbr -a cut   uu-cut  
abbr -a date   uu-date  
abbr -a dd   uu-dd  
abbr -a du   uu-du  
abbr -a echo   uu-echo  
abbr -a hostname   uu-hostname  
abbr -a id   uu-id  
abbr -a kill   uu-kill  
abbr -a ln   uu-ln  
abbr -a mkdir   uu-mkdir  
abbr -a mv   uu-mv  
abbr -a pwd   uu-pwd  
abbr -a seq   uu-seq  
abbr -a sleep   uu-sleep  
abbr -a sort   uu-sort  
abbr -a tac   uu-tac  
abbr -a tail   uu-tail  
abbr -a tee   uu-tee  
abbr -a touch   uu-touch  
abbr -a tr   uu-tr  
abbr -a uname   uu-uname  
abbr -a uniq   uu-uniq  
abbr -a wc   uu-wc  
abbr -a who   uu-who  
abbr -a whoami   uu-whoami  
abbr -a yes   uu-yes  
