-- vim.g.rustaceanvim = {
--   tools = {
--   },
--   server = {
--     capabilities = require("cmp_nvim_lsp").default_capabilities(),
--     on_attach = function(client, bufnr)
--       -- you can also put keymaps in here
--     end,
--     settings = {
--       -- rust-analyzer language server configuration
--       ['rust-analyzer'] = {
--       },
--     },
--   },
--   -- DAP configuration
--   dap = {
--     adapter = {
--       type = "executable",
--       command = "lldb-vscode",
--       name = "rt_lldb",
--    },
--   }
-- }
